name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: 
        npm install
        npm run build

    - name: Check if gh-pages branch exists
      run:
          git checkout -B gh-pages


    - name: Clear existing content
      run: git rm -rf .

    - name: Copy to Build Branch
      run: cp -r build/. .

    - name: Commit and Push
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Auto-build and deploy"
        git push origin gh-pages
